default_context:
  project_name: '{{ SERVICE_NAME }}'
  project_slug: '{{ SERVICE_NAME }}'
  domain_main: '{{ SERVICE_NAME }}.com'
  domain_staging: 'stag.{{ SERVICE_NAME }}.com'
  docker_swarm_stack_name_main: '{{ SERVICE_NAME }}-com'
  docker_swarm_stack_name_staging: 'stag-{{ SERVICE_NAME }}-com'
  secret_key: '04ecee494832d84f03b1d59574043e84d0b03fe26dbd27c700e5dd60b5cae64f'
  first_superuser: 'admin@{{ SERVICE_NAME }}.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.{{ SERVICE_NAME }}.com", "https://stag.{{ SERVICE_NAME }}.com", "https://{{ SERVICE_NAME }}.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@{{ SERVICE_NAME }}.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: '{{ SERVICE_NAME }}.com'
  traefik_constraint_tag_staging: 'stag.{{ SERVICE_NAME }}.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: 'https://7cfd60f0751d4cc1b03bd2acd56ea5e4@o419007.ingest.sentry.io/5516233'
  docker_image_prefix: 'docker.pkg.github.com/alewkinr/lyra/'
  docker_image_backend: 'docker.pkg.github.com/alewkinr/lyra/backend'
  docker_image_celeryworker: 'docker.pkg.github.com/alewkinr/lyra/celeryworker'
  docker_image_frontend: 'docker.pkg.github.com/alewkinr/lyra/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app_1/app_1/email-templates/**]
  _template: ./
