default_context:
  project_name: '{{ SERVICE_NAME }}'
  project_slug: '{{ SERVICE_NAME }}'
  domain_main: '{{ SERVICE_NAME }}.com'
  domain_staging: 'stag.{{ SERVICE_NAME }}.com'
  docker_swarm_stack_name_main: '{{ SERVICE_NAME }}-com'
  docker_swarm_stack_name_staging: 'stag-{{ SERVICE_NAME }}-com'
  secret_key: 'SECRET_KEY'
  first_superuser: 'admin@{{ SERVICE_NAME }}.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.{{ SERVICE_NAME }}.com", "https://stag.{{ SERVICE_NAME }}.com", "https://{{ SERVICE_NAME }}.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@{{ SERVICE_NAME }}.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@{{ SERVICE_NAME }}.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: '{{ SERVICE_NAME }}.com'
  traefik_constraint_tag_staging: 'stag.{{ SERVICE_NAME }}.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: 'SENTRY_DSN'
  docker_image_prefix: 'DOCKER_IMAGE_PREFIX'
  docker_image_backend: 'DOCKER_IMAGE_BACKEND'
  docker_image_celeryworker: 'DOCKER_IMAGE_CELERYWORKER'
  docker_image_frontend: 'DOCKER_IMAGE_FRONTEND'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app_1/app_1/email-templates/**]
  _template: ./
